const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const database = require('./src/model/database')
const staff = require('./src/model/staff.model')
const homeController = require("./src/controller/home.controller")
const PORT = 4332;
app.set("view engine","ejs")
app.set("views","./src/views")
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.get('/',homeController.getHomePage)
app.post('/',homeController.getHomePage)
app.get('/delete/:id',homeController.deleteHomePage)
app.get("/edit/:id",homeController.getEditHomePage)
app.post("/edit/:id",homeController.postEditHomePage)
app.get("/add",homeController.getAddPage)
app.post("/add",homeController.postAddPage)
app.listen(PORT,()=>{
    console.log(`http://localhost:${PORT}`)
})